// The current version of OCAP.
#ifndef OCAP_SCRIPT_VERSION_HPP
#define OCAP_SCRIPT_VERSION_HPP

// DEFINE: VERSION
#define VERSION 2.1

// DEFINE: VERSION_STR
#define VERSION_STR 2.1.0

// DEFINE: VERSION_AR
#define VERSION_AR 2,1,0

// DEFINE: VERSION_REQUIRED
#define VERSION_REQUIRED 2.10

#define MAJOR 2
#define MINOR 1
#define PATCH 0
#define BUILD 0

#endif
