ocap_autoStart = true; // Automatically start OCAP recordings at session start.
ocap_minPlayerCount = 15; // recording will only begin if this many players are in the server
ocap_minMissionTime = 20; // missions must last at least this many minutes to be saved
ocap_frameCaptureDelay = 1;
ocap_saveMissionEnded = true; // automatically save mission with default settings on the "MPEnded" event handler trigger
ocap_preferACEUnconscious = true; // if true, ACE3 medical unconscious state will be used. if false, will check vanilla A3 system
ocap_excludeClassFromRecord = ["ACE_friesAnchorBar", "GroundWeaponHolder", "WeaponHolderSimulated"]; // excludes specific class names from recordings
ocap_excludeKindFromRecord = []; // use isKindOf checking to exclude one or more hierarchies of objects from recording
ocap_excludeMarkerFromRecord = ["SystemMarker_"]; // excludes markers with any of these strings in their markerName
ocap_trackTimes = false; // continously track times -- set true for missions with accelerated or skipped time
ocap_trackTimeInterval = 10; // track time every X capture frame
ocap_isDebug = false; // extra logging messages
