ocap_nameServer = 'TvT';
ocap_minPlayerCount = 60;
ocap_frameCaptureDelay = 1;
ocap_excludeClassFromRecord = ["ACE_friesAnchorBar"]; // excludes specific class names from recordings
ocap_excludeMarkerFromRecord = ["SystemMarker_"]; // excludes markers with any of these strings in their name
ocap_saveMissionEnded = true;
ocap_minMissionTime = 90;
ocap_isDebug = false;
ocap_trackTimes = false; // continously track times
ocap_trackTimeInterval = 10; // track time every X capture frame
