name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Run HEMTT release
        run: hemtt release

      - name: Upload release assets
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v2
        with:
          files: releases/ocap-latest.zip
