name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Run HEMTT release
        run: hemtt release

      - name: Upload release assets
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          files: releases/ocap-latest.zip
